Feature/testing w rtl
NewIncome/math-mag-co-calculator pull request #8
Opened 2021-01-15 22:01 UTC by NewIncome

Made required tests according to Microverse's Math-Magicians Testing Project

2021-01-16 12:04 UTC, wathigo requested changes
## Changes Required :o: 
Great job adding tests.
Let's make some changes before we move on.

### REQUIRED
* Use jest snapshots to make sure that all the elements in the Home, Calculator, and Quote pages have been displayed. 
![Screenshot from 2021-01-16 06-57-22](https://user-images.githubusercontent.com/44072711/104811281-6a188680-57c8-11eb-98ec-f4f05600a313.png)
* Include jest in devDependencies by running `npm install --save-dev jest`.

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2021-01-19 19:01 UTC, NewIncome commented
> ## Changes Required o
> 
> Great job adding tests.
> Let's make some changes before we move on.
> ### REQUIRED
> 
>     * Use jest snapshots to make sure that all the elements in the Home, Calculator, and Quote pages have been displayed.
>       ![Screenshot from 2021-01-16 06-57-22](https://user-images.githubusercontent.com/44072711/104811281-6a188680-57c8-11eb-98ec-f4f05600a313.png)
> 
>     * Include jest in devDependencies by running `npm install --save-dev jest`.
> 
> 
> **After making the changes, submit another request for review.**
> 
> **Happy Coding computer Simon Wathigo**

Hi @wathigo 
Please need some help.
I've been getting an error and can't manage to solve it. Regarding React tests.
I posted the seek for help in the Full-time student's Slack channel.

By the way, Jest was already in my devDependencies but anyway I ran that line to install it again.

2021-01-19 21:22 UTC, bellom approved these changes
## Hi @NewIncome  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-01-19 21:22 UTC, bellom commented on src/components/App.js
> +      // </section>
It’s better to delete commented code. If you need to review a previous version of your code, use git history. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

**_Kindly remove before merging._**

2021-01-19 23:36 UTC, merged